# Standard R packages (Don't count these as dependencies in PKGBUILD)
notdepend:
  - r-kernsmooth
  - r-mass
  - r-matrix
  - r-base
  - r-boot
  - r-class
  - r-cluster
  - r-compiler
  - r-datasets
  - r-foreign
  - r-grdevices
  - r-graphics
  - r-grid
  - r-lattice
  - r-methods
  - r-mgcv
  - r-nlme
  - r-nnet
  - r-parallel
  - r-rpart
  - r-spatial
  - r-splines
  - r-stats
  - r-stats4
  - r-survival
  - r-tcltk
  - r-tools
  - r-translations
  - r-utils

# Manual override of PKGBUILD fields. Blank strings will be ignored.
# To override using a literal blank string, use 'null'.
# Package keys should use the CRAN name, but case does not matter.
override:
  R2WinBUGS:
    pkgname: ''
    pkgver: ''
    pkgdesc: "Running 'WinBUGS' and 'OpenBUGS'"
    url: ''
    arch: ''
    license: ''
    depends: ''
    optdepends: ''

# In my experience, icu required as dependency for successful build of
# stringi
  stringi:
    pkgname: ''
    pkgver: ''
    pkgdesc: ''
    url: ''
    arch: ''
    license: ''
    depends: "'r>=2.14', 'icu'"
    optdepends: ''

# Removing '.' from data.table package name and renaming R.utils
# optional dependency
  data.table:
    pkgname: 'r-datatable'
    pkgver: ''
    pkgdesc: ''
    url: ''
    arch: ''
    license: ''
    depends: ''
    optdepends: "'r-bit64' 'r-curl' 'r-utils' 'r-knitr' 'r-xts' 'r-nanotime' 'r-zoo'"
