#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'

args = ARGV

# Create an Arch Linux PKGBUILD file from an R package name available
# on CRAN.
class CreatePkgBuild
  def initialize(pkg)
    @pkg = pkg
    url = "https://cran.r-project.org/web/packages/#{@pkg}/index.html"
    doc = Nokogiri::HTML(open(url))
    @cran_page_body = doc.at('body').text
  end

  # Parse CRAN page take for needed info.
  def cran_page_parse
    depends = @cran_page_body.split("Depends:\n")[1].split("\n")[0]
  end
end

#  def fill_pkgbuild_template
#    pkgbuild = "# Generated by pacr: github.com/ryw89/pacr
# _cranname=#{pkg}
# _cranver=#{cran_pkgver}
# pkgname=#{arch_pkgname}
# pkgver=#{arch_pkgver}
# pkgrel=1
# pkgdesc=\"#{pkgdesc}\"
# url=\"https://cran.r-project.org/package=#{pkg}\"
# arch=('i686' 'x86_64')
# license=(#{license})
# depends=(#{depends})
# optdepends=(#{optdepends})
# source=(\"http://cran.r-project.org/src/contrib/${_cranname}_${_cranver}.tar.gz\")
# md5sums=(#{md5sums})
#
# package() {
#    mkdir -p ${pkgdir}/usr/lib/R/library
#    cd ${srcdir}
#    R CMD INSTALL ${_cranname} -l ${pkgdir}/usr/lib/R/library
# }"
#  end
